FROM python:3.11-bullseye

WORKDIR /app/

COPY ./requirements.txt ./app .env* /app/

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers", "--forwarded-allow-ips", "*"]


